version: '2'
services:
    data:
      image: cogniteev/echo
      # This is the path to your project files (..), will map to /var/app in the container
      volumes:
        - ..:/var/app

    php-cli:
      image: arkanmgerges/php-cli:1.0

    php-ssh:
      image: arkanmgerges/php-ssh:1.0
      ports:
        - "1122:22"
      volumes_from:
        - data

    php-fpm:
      image: arkanmgerges/php-fpm:1.0
      working_dir: /var/app
      volumes_from:
        - data
      # This is where you can collect xdebug profiling data (set your path), this will map to the /tmp in the container
      volumes:
        - ../.tmp:/tmp
      networks:
        - net01

    web-nginx:
      image: nginx:latest
      depends_on:
        - php-fpm
      ports:
        - "8080:80"
      volumes_from:
        - data
      volumes:
        - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
      networks:
        - net01

    redis:
      container_name: redis01
      image: redis:3.0.7
      ports:
        - "6379:6379"

    elasticsearch01:
      container_name: es01
      image: elasticsearch:5.0.1
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - net02

    kibana:
      image: kibana:5.0.1
      networks:
        - net02
      ports:
        - "5601:5601"
      environment:
      # Here you need to provide your elastic search url
        ELASTICSEARCH_URL: http://192.168.99.100:9200

networks:
    net01:
      driver: bridge
    net02:
      driver: bridge